define(
//begin v1.x content
    ({
        BoxAndWhiskerOperator:"箱ひげ図",
        HadoopBoxAndWiskerOperator:"箱ひげ図",
        DbTableOperator:"DBテープル",
        BarChartAnalysisOperator:"バーチャート",
        CorrelationAnalysisOperator:"相関分析",
        FrequencyAnalysisOperator:"頻度分析",
        HistogramOperator:"ヒストグラム分析",
        InformationValueAnalysisOperator:"情報価値分析",
        UnivariateOperator:"単変量分析",
        ValueAnalysisOperator:"要約統計量",
        AggregateOperator:"集計",
        CustomizedOperator:"カスタムオペレーター",
        NormalizationOperator:"正規化",
        ReplaceNullOperator:"Null値置換",
        IntegerToTextOperator:"数値型からテキスト型へ",
        PivotOperator:"ピボット",
        FilterOperator:"行フィルター",
        TableJoinOperator:"テープル結合",
        VariableOperator:"変数",
        RandomSamplingOperator:"無作為抽出法",
        StratifiedSamplingOperator:"層別抽出法",
        SampleSelectorOperator:"標本セレクター",
        AssociationOperator:"関連ルール",
        CartOperator:"CART木",
        DecisionTreeOperator:"決定木",
        KMeansOperator:"K平均法",
        LinearRegressionOperator:"線形回帰",
        LogisticRegressionOperator:"ロジスティック回帰",
        ModelOperator:"模型オペレーター",
        NaiveBayesOperator:"単純ベイズ",
        NeuralNetworkOperator:"神経回路網",
        TimeSeriesOperator:"時系列",
        LinearRegressionPredictOperator:"線形回帰予測",
        LogisticRegressionPredictOperator:"ロジスティック回帰予測",
        NaiveBayesPredictOperator:"単純ベイズ予測",
        NeuralNetworkPredictOperator:"神経回路網予測",
        TimeSeriesPredictOperator:"時系列予測",
        TreePredictOperator:"木予測",
        GoodnessOfFitOperator:"適合度",
        LIFTOperator:"リフト",
        ROCOperator:"ROC",
       // ProductRecommendationOperator:"ZH product recommendation",
       // ProductRecommendationEvaluationOperator:"ZH production evaluation",
        SVMNoveltyDetectionOperator:"ノベルティ検知SVM",
        SVMClassificationOperator:"分類SVM",
        SVMRegressionOperator:"回帰SVM",
        SVMPredictOperator:"SVM予測",
        SVDOperator:"SVD",
        SVDLanczosOperator:"SVD",
        SVDCalculatorOperator:"SVD計算器",
        SVDLanczosCalculatorOperator:"SVD計算器",
        ColumnFilterOperator:"列フィルター",
        VariableSelectionAnalysisOperator:"変数選択分析",
        SQLExecuteOperator:"実行可能なSQL句",
        AdaboostOperator:"Adaboost",
        AdaboostPredictOperator:"Adaboost予測",
        PCAOperator:"主成分分析",
        WOEOperator:"証拠の重み付け",
        WOETableGeneratorOperator:"WOEテーブル生成器",
        ScatterMatrixOperator:"散布図行列",
        TableSetOperator:"テーブルセット",
        PLDATrainerOperator:"LDA分析",
        PLDAPredictOperator:"LDA予測",
        SubFlowOperator:"サブフロー",
        EMClusteringOperator:"EMクラスタ",
        EMClusteringPredictOperator:"EMクラスタ予測",
        ScatterPlotOperator:"散布図",
        //UnivariateExplorerOperator:"ZH univariate",
        //UnivariateOperator:"ZH Univariate",
        //BoxAndWhiskerOperator:"ZH box and whisker",
        HadoopFileOperator:"Hadoopファイル",
        HadoopRowFilterOperator:"行フィルター",
        HadoopVariableOperator:"変数",
        HadoopAggregateOperator:"集計",
        HadoopFrequencyAnalysisOperator:"頻度分析",
        HadoopValueAnalysisOperator:"要約統計量",
        HadoopHistogramOperator:"ヒストグラム分析",
        HadoopUnionOperator: "テーブルセット",
        HadoopJoinOperator: "テープル結合",
        HadoopBarChartOperator: "バーチャート",
        HadoopReplaceNullOperator:"Null値置換",
        HadoopScatterPlotMatrixOperator:"散布図行列",
        HadoopNormalizationOperator:"正規化",
        HadoopKmeansOperator:"K平均法",
        HadoopRandomSamplingOperator:"無作為抽出法",
        HadoopSampleSelectorOperator:"標本セレクター",
        HadoopLinearRegressionOperator:"線形回帰",
        HadoopLinearRegressionPredictOperator:"線形回帰予測",
        HadoopLogisticRegressionOperator:"ロジスティック回帰",
        HadoopLogisticRegressionPredictOperator:"ロジスティック回帰予測",
        HadoopTimeSeriesOperator:"時系列",
        HadoopTimeSeriesPredictOperator:"時系列予測",
        HadoopVariableSelectionAnalysisOperator:"変数選択分析",
        CopyToDBOperator:"データベースにコピー",
        CopytoHadoopOperator:"Hadoopにコピー",
        NoteOperator:"ノート",
        HadoopROCOperator:"ROC",
        HadoopLiftOperator:"リフト",
        HadoopGoodnessOfFitOperator:"適合度",
        HadoopPigExecuteOperator:"実行可能なPigスクリプト",
        HadoopDecisionTreeOperator:"決定木",
        RandomForestOperator:"ランダムフォレスト",
        RandomForestPredictOperator:  "ランダムフォレスト予測",
        HadoopPivotOperator:"ピボット",
        HadoopColumnFilterOperator:"列フィルター",
        HadoopDecisionTreePredictOperator:"木予測",
        HadoopNaiveBayesOperator:"単純ベイズ",
        HadoopNaiveBayesPredictOperator: "単純ベイズ予測",
        HadoopConfusionOperator:"Confusion Matrix"


    })
//end v1.x content
);
