/**
 * COPYRIGHT   2011 (c) Alpine Data Labs. All Rights Reserved.    
 *
 * ResourceInfo.java
 * 
 * Author sam_zang
 * 
 * Version 2.0
 * 
 * Date Jun 22, 2011
 */

package com.alpine.miner.impls.resource;

/**
 * @author sam_zang
 * 
 */
public abstract class ResourceInfo {
	
	public enum ResourceType {
		Public, Group, Personal
	};

	public static final String ID = "id";
	public static final String CREATE_USER = "createUser";
	public static final String CREATE_TIME = "createTime";
	public static final String MODIFIED_USER = "modifiedUser";
	public static final String MODIFIED_TIME = "modifiesTime";
	public static final String TYPE = "resourceType";
	public static final String CATEGORIES = "categories";
	public static final String GROUP_NAME = "groupName";
	public static final String VERSION = "version";
	public static final String COMMENTS = "comments"; 
	
	
	protected ResourceInfo(String user, String id, ResourceType type) {
		this.id = id;
		this.createUser = user;
		this.modifiedUser = user;

		this.groupName = "";
		this.createTime = System.currentTimeMillis();
		this.modifiedTime = System.currentTimeMillis();
		this.type = type;
	}
	
	protected ResourceInfo() { 
		this.createTime = System.currentTimeMillis();
		this.modifiedTime = System.currentTimeMillis();
		type = ResourceType.Personal; 
		this.groupName = "";
	}
	private String comments = null;
	private String version ="";
	private String id;
	private String createUser;
	private Long createTime;
	private String modifiedUser;
	private Long modifiedTime;
	private ResourceType type;
	private String[] categories;
	private String groupName;
	
	/**
	 * @return the groupName
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * @param groupName the groupName to set
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	// key is generated by persistence. It is
	// implementation and platform dependent.
	// It is not stored.
	private String key;

	/**
	 * @return the key
	 */
	public String getKey() {
		return key;
	}

	/**
	 * @param key the key to set
	 */
	public	void setKey(String key) {
		this.key = key;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * @param createUser
	 *            the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime
	 *            the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the modifiedUser
	 */
	public String getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * @param modifiedUser
	 *            the modifiedUser to set
	 */
	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	/**
	 * @return the modifiedTime
	 */
	public Long getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * @param modifiedTime
	 *            the modifiedTime to set
	 */
	public void setModifiedTime(Long modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * @return the resourceType
	 */
	public ResourceType getResourceType() {
		return type;
	}

	/**
	 * @param resourceType
	 *            the resourceType to set
	 */
	public void setResourceType(ResourceType resourceType) {
		this.type = resourceType;
	}

	/**
	 * @return
	 */
	public String[] getCategories() {
		return categories;
	}

	/**
	 * @param list
	 */
	public void setCategories(String[] list) {
		categories = list;
	}


	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
}
