drop function if exists alpine_miner_adaboost_changep(text, text, text, text, text, text, text[]) cascade;
drop function if exists alpine_miner_adaboost_changep(text, text) cascade;
drop function if exists alpine_miner_adaboost_initpre( text,  text,  text,  text[], boolean) cascade;
drop function if exists alpine_miner_adaboost_initpre(text, text, text, text[]) cascade;
drop function if exists alpine_miner_adaboost_initpre(text, text, text[]) cascade;
drop function if exists alpine_miner_adaboost_inittra(text, text, text, text, text[]) cascade;
drop function if exists alpine_miner_adaboost_inittra(text, text) cascade;
drop function if exists alpine_miner_adaboost_prere(text, text, text[], integer) cascade;
drop function if exists alpine_miner_adaboost_prere(text, text, text[]) cascade;
drop function if exists alpine_miner_adaboost_prestep(text, text, text, double precision, text[]) cascade;
drop function if exists alpine_miner_adaboost_prestep(text, text,  double precision, text[]) cascade;
drop function if exists alpine_miner_adaboost_sample(text, text, text) cascade;
drop function if exists alpine_miner_adaboost_trare(text, text) cascade;
drop function if exists alpine_miner_adaboost_sample(text) cascade;
drop function if exists alpine_miner_ar_predict(integer, double precision[], text[], text, text) cascade;
drop function if exists alpine_miner_ar_predict(integer, float[], text[], text, text) cascade;
drop function if exists alpine_miner_contains(text[], text) cascade;
drop function if exists alpine_miner_corr_accum(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_corr_combine(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_corr_final(double precision[]) cascade;
drop function if exists alpine_miner_covar_accum(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_covar_combine(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_covar_final(double precision[]) cascade;
drop function if exists alpine_miner_covar_sam_accum(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_covar_sam_combine(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_covar_sam_final(double precision[]) cascade;
drop function if exists alpine_miner_dot_product(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_dot_product(float[], float[]) cascade;
drop function if exists alpine_miner_float8_mregr_accum(double precision[], double precision, double precision[]) cascade;
drop function if exists alpine_miner_float8_mregr_combine(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_generate_random_table(text, bigint) cascade;
drop function if exists alpine_miner_get_array_count(text[]) cascade;
drop function if exists alpine_miner_get_dbtype() cascade;
drop function if exists alpine_miner_getdistribution(text, text) cascade;
drop function if exists alpine_miner_has_novel_product(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_has_novel_product(float[], float[]) cascade;
drop function if exists alpine_miner_initpca(text, text, text[], text, text) cascade;
drop function if exists alpine_miner_instr(character varying, character varying) cascade;
drop function if exists alpine_miner_instr(varchar, varchar) cascade;
drop function if exists alpine_miner_instr(character varying, character varying, integer) cascade;
drop function if exists alpine_miner_instr(varchar, varchar, integer) cascade;
drop function if exists alpine_miner_kmeans_c(text, text, text[], integer, text, integer, integer, integer, integer) cascade;
drop function if exists alpine_miner_kmeans_c_1_5(text, text, text[], integer, text, text, text, integer, integer, integer, integer) cascade;
drop function if exists alpine_miner_kmeans_c_array(text, text, text[], integer, text, integer, integer, integer, integer) cascade;
drop function if exists alpine_miner_kmeans_c_array_1_5(text, text, text[], integer, text, text, text, integer, integer, integer, integer) cascade;
drop function if exists alpine_miner_kmeans_c_array_array(text, text, text[], integer[], integer, text, text, text, integer, integer, integer, integer) cascade;
drop function if exists alpine_miner_kmeans_distance(integer, text[], integer, integer) cascade;
drop function if exists alpine_miner_kmeans_distance_loop(double precision[], double precision[], integer, integer) cascade;
drop function if exists alpine_miner_kmeans_distance_result(double precision[], double precision[], integer, integer) cascade;
drop function if exists alpine_miner_kmeans_sp(text, text, text[], integer, text, integer, integer, integer, integer) cascade;
drop function if exists alpine_miner_kmeans_sp_1_5(text, text, text[], integer, text, integer, integer, integer, integer) cascade;
drop function if exists alpine_miner_lr_ca_beta_accum(double precision[], double precision[], double precision[], boolean, double precision, integer, integer) cascade;
drop function if exists alpine_miner_lr_ca_fitness(double precision[], double precision[], boolean, double precision, integer) cascade;
drop function if exists alpine_miner_lr_ca_he_accum(double precision[], double precision[], double precision[], boolean, double precision) cascade;
drop function if exists alpine_miner_lr_ca_he_de_accum(double precision[], double precision[], double precision[], boolean, double precision, integer) cascade;
drop function if exists alpine_miner_lr_ca_he(float[], float[],  boolean, float) cascade;
drop function if exists alpine_miner_lr_ca_fitness(float[], float[], boolean, float, integer) cascade;
drop function if exists alpine_miner_lr_ca_pi(float[], float[], boolean) cascade;
drop function if exists alpine_miner_lr_ca_pi(double precision[], double precision[], boolean) cascade;
drop function if exists alpine_miner_lr_ca_beta(float[], float[],  boolean, float,  integer) cascade;
drop function if exists alpine_miner_lr_ca_beta(float[], float[],  boolean, float,  integer，integer) cascade;
drop function if exists alpine_miner_lr_ca_he_de(float[], float[],  boolean, float,  integer) cascade;

drop function if exists alpine_miner_lr_combine(double precision[], double precision[]) cascade;
DROP AGGREGATE IF EXISTS alpine_miner_make_vec (int, float, int);
DROP AGGREGATE IF EXISTS alpine_miner_mregr_coef (DOUBLE PRECISION,DOUBLE PRECISION[]);
DROP AGGREGATE IF EXISTS alpine_miner_corr(DOUBLE PRECISION[]);
drop function if exists alpine_miner_make_vec_prefunc(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_make_vec_prefunc(float[], float[]) cascade;
drop function if exists alpine_miner_make_vec_sfunc(double precision[], integer, double precision, integer) cascade ;
drop function if exists alpine_miner_make_vec_sfunc(float[], integer, float, integer) cascade ;
drop function if exists alpine_miner_nb_ca_confidence(text[], integer[], text[], double precision[], text[], double precision[], double precision[], double precision[]) cascade;
drop function if exists alpine_miner_nb_ca_confidence(text[], integer[], text[], float[], text[], float[],float[], float[]) cascade;

drop function if exists alpine_miner_nb_ca_deviance(text[], integer[], text[], double precision[], text, text[], double precision[], double precision[], double precision[]) cascade;
drop function if exists alpine_miner_nb_ca_deviance(text[], integer[], text[], float[], text, text[], float[], float[], float[]) cascade;
drop function if exists alpine_miner_nb_ca_prediction(float[], text[]) cascade;
drop function if exists alpine_miner_nb_ca_prediction(double precision[], text[]) cascade;
drop function if exists alpine_miner_nn_ca_change(double precision[], double precision[], double precision[], double precision[], integer[], integer, double precision, double precision, integer, boolean, boolean, double precision, integer) cascade;
drop function if exists alpine_miner_nn_ca_o(double precision[], double precision[], double precision[], double precision[], integer[], integer, double precision, double precision, integer, boolean, boolean) cascade;
drop function if exists alpine_miner_nn_ca_o(float[], float[], float[], float[], integer[], integer,float, float, integer, boolean, boolean) cascade;
drop function if exists alpine_miner_nn_ca_change(float[], float[], float[], float[], integer[], integer, float, float, integer, boolean, boolean, float, integer) cascade;

drop function if exists alpine_miner_null_to_0(bigint) cascade;
drop function if exists alpine_miner_null_to_0(double precision) cascade;
drop function if exists alpine_miner_null_to_0(float) cascade;
drop function if exists alpine_miner_online_sv_cl(text, text, text, text, integer, integer, double precision, double precision, double precision) cascade;
drop function if exists alpine_miner_online_sv_cl(text, text, text, text, integer, integer, float, FLOAT8, FLOAT8) cascade;

drop function if exists alpine_miner_online_sv_nd(text, text, text, integer, integer, double precision, double precision, double precision) cascade;
drop function if exists alpine_miner_online_sv_nd(text, text, text, integer, integer, float, FLOAT8, FLOAT8) cascade;

drop function if exists alpine_miner_online_sv_reg(text, text, text, text, integer, integer, double precision, double precision, double precision, double precision) cascade;
drop function if exists alpine_miner_online_sv_reg(text, text, text, text, integer, integer, float, FLOAT8, FLOAT8, FLOAT8) cascade;

drop function if exists alpine_miner_pcaresult(text, text[], text, text[], text, integer, text) cascade;
drop function if exists alpine_miner_pcaresult(double precision[], double precision[]) cascade;
drop function if exists alpine_miner_pr(text, text, text, text, text, text, text, text, integer, integer, double precision, integer, integer, double precision, text, text, integer) cascade;
drop function if exists alpine_miner_pr(text, text, text, text, text, text, text, text, integer, integer, FLOAT, integer, integer, FLOAT, text, text, integer) cascade;
drop function if exists alpine_miner_pr_eval(text, text, text, text, text, text, text, text, text, text) cascade;
drop function if exists alpine_miner_split(text, text) cascade;
drop function if exists alpine_miner_svd(text, text, text, text, integer, double precision, double precision, double precision, double precision, integer, integer, double precision, integer, double precision, integer, text, text, integer, integer) cascade;
drop function if exists alpine_miner_svd(text, text, text, text, integer, float, float, float, float, integer, integer, float, integer, float, integer, text, text, integer, integer) cascade;
drop function if exists alpine_miner_svd_l(text, text, text, text, text, text, integer, double precision) cascade;
drop function if exists alpine_miner_svm_cls_update(alpine_miner_svm_model, double precision[], double precision, double precision, double precision, integer, integer, double precision) cascade;
drop function if exists alpine_miner_svm_cls_update(alpine_miner_svm_model, FLOAT8[], FLOAT8, FLOAT8, FLOAT8, integer, integer, FLOAT8) cascade;

drop function if exists alpine_miner_svm_nd_update(alpine_miner_svm_model, double precision[], double precision, double precision, integer, integer, double precision) cascade;
drop function if exists alpine_miner_svm_nd_update(alpine_miner_svm_model, FLOAT8[], FLOAT8, FLOAT8, integer, integer, FLOAT8) cascade;

drop function if exists alpine_miner_svm_predict_sub(integer, integer, double precision[], double precision[], double precision[], integer, integer, double precision) cascade;
drop function if exists alpine_miner_svm_predict_sub(integer, integer, float8[], float8[], float8[], integer, integer, float8) cascade;
drop function if exists alpine_miner_svm_reg_update(alpine_miner_svm_model, double precision[], double precision, double precision, double precision, double precision, integer, integer, double precision) cascade;
drop function if exists alpine_miner_svm_reg_update(alpine_miner_svm_model, FLOAT8[], FLOAT8, FLOAT8, FLOAT8, FLOAT8, integer, integer, FLOAT8) cascade;
DROP AGGREGATE IF EXISTS alpine_miner_svm_reg_agg (float8[], float8, float8, float8, float8, int, int, float8);
DROP AGGREGATE IF EXISTS alpine_miner_svm_cls_agg (float8[], float8, float8, float8, int, int, float8);
DROP AGGREGATE IF EXISTS alpine_miner_svm_nd_agg (float8[], float8, float8, int, int, float8);
DROP AGGREGATE IF EXISTS alpine_miner_covar(DOUBLE PRECISION[]);
DROP AGGREGATE IF EXISTS alpine_miner_covar_sam(DOUBLE PRECISION[]);
drop function if exists alpine_miner_svs_predict(alpine_miner_svm_model, double precision[], integer, integer, double precision) cascade;
drop function if exists alpine_miner_svs_predict(alpine_miner_svm_model, float8[], integer, integer, float8) cascade;
drop type IF EXISTS alpine_miner_svm_model cascade;