define(
//begin v1.x content
    ({
    	BoxAndWhiskerOperator:"箱型图",
        HadoopBoxAndWiskerOperator:"箱型图",
        DbTableOperator:"数据表",
        BarChartAnalysisOperator:"柱状图",
        CorrelationAnalysisOperator:"相关分析",
        FrequencyAnalysisOperator:"值频率分析",
        HistogramOperator:"直方图",
        InformationValueAnalysisOperator:"信息值分析",
        UnivariateOperator:"单变量分析",
        ValueAnalysisOperator:"值分析",
        AggregateOperator:"聚合器",
        CustomizedOperator:"自定义操作单元",
        NormalizationOperator:"规范化",
        ReplaceNullOperator:"空值替换",
        IntegerToTextOperator:"数字转换",
        PivotOperator:"透视分析",
        FilterOperator:"数据行筛选器",
        TableJoinOperator:"表连接",
        VariableOperator:"变量器",
        RandomSamplingOperator:"随机抽样",
        StratifiedSamplingOperator:"分层抽样",
        SampleSelectorOperator:"抽样数据表选择",
        AssociationOperator:"关联规则分析",
        CartOperator:"分类回归树分析",
        DecisionTreeOperator:"决策树",
        KMeansOperator:"KMeans聚类",
        LinearRegressionOperator:"线性回归",
        LogisticRegressionOperator:"逻辑回归",
        ModelOperator:"模型",
        NaiveBayesOperator:"朴素贝叶斯",
        NeuralNetworkOperator:"神经网络",
        TimeSeriesOperator:"时间序列分析",
        LinearRegressionPredictOperator:"线性回归预测",
        LogisticRegressionPredictOperator:"逻辑回归预测",
        NaiveBayesPredictOperator:"朴素贝叶斯预测",
        NeuralNetworkPredictOperator:"神经网络预测",
        TimeSeriesPredictOperator:"时间序列预测",
        TreePredictOperator:"树预测",
        GoodnessOfFitOperator:"拟合优度模型评估",
        LIFTOperator:"提升度模型评估",
        ROCOperator:"ROC-AUC模型评估",
       // ProductRecommendationOperator:"ZH product recommendation",
       // ProductRecommendationEvaluationOperator:"ZH production evaluation",
        SVMNoveltyDetectionOperator:"支持向量机新颖检测",
        SVMClassificationOperator:"支持向量机分类",
        SVMRegressionOperator:"支持向量机回归",
        SVMPredictOperator:"支持向量机预测",
        SVDOperator:"SVD",
        SVDLanczosOperator:"svd lanczos",
        SVDCalculatorOperator:"SVD计算器",
        SVDLanczosCalculatorOperator:"svd lanczos计算器",
        ColumnFilterOperator:"列筛选器",
        VariableSelectionAnalysisOperator:"变量选择分析",
        SQLExecuteOperator:"可执行SQL分析",
        AdaboostOperator:"Adaboost",
        AdaboostPredictOperator:"Adaboost预测",
        PCAOperator:"主成分分析",
        WOEOperator:"表征权重分析",
        WOETableGeneratorOperator:"表征权重生成器",
        ScatterMatrixOperator:"散点图矩阵",
        TableSetOperator:"表集合",
        PLDATrainerOperator:"LDA 分析",
        PLDAPredictOperator:"LDA 预测",
        SubFlowOperator:"子流程",
        EMClusteringOperator:"EM聚类分析",
        EMClusteringPredictOperator:"EM聚类预测",
        ScatterPlotOperator:"散点图",
        //UnivariateExplorerOperator:"ZH univariate",
        //UnivariateOperator:"ZH Univariate",
        //BoxAndWhiskerOperator:"ZH box and whisker",
        HadoopFileOperator:"hadoop文件",
        HadoopRowFilterOperator:"数据行筛选器",
        HadoopVariableOperator:"变量器",
        HadoopAggregateOperator:"聚合器",
        HadoopFrequencyAnalysisOperator:"值频率分析",
        HadoopValueAnalysisOperator:"值分析",
        HadoopHistogramOperator:"直方图",
        HadoopUnionOperator: "表集合",
        HadoopJoinOperator: "表连接",
        HadoopBarChartOperator: "柱状图",
        HadoopReplaceNullOperator:"空值替换",
        HadoopScatterPlotMatrixOperator:"散点图矩阵",
        HadoopNormalizationOperator:"规范化",
        HadoopKmeansOperator:"KMeans聚类",
        HadoopRandomSamplingOperator:"随机抽样",
        HadoopSampleSelectorOperator:"抽样数据表选择",
        HadoopLinearRegressionOperator:"线性回归",
        HadoopLinearRegressionPredictOperator:"线性回归预测",
        HadoopLogisticRegressionOperator:"逻辑回归",
        HadoopLogisticRegressionPredictOperator:"逻辑回归预测",
        HadoopTimeSeriesOperator:"时间序列",
        HadoopTimeSeriesPredictOperator:"时间序列预测",
        HadoopVariableSelectionAnalysisOperator:"变量选择分析",
        CopyToDBOperator:"复制到数据库",
        CopytoHadoopOperator:"复制到Hadoop",
        NoteOperator:"注释",
        HadoopROCOperator:"ROC-AUC模型评估",
        HadoopLiftOperator:"提升度模型评估",
        HadoopGoodnessOfFitOperator:"拟合优度模型评估",
        HadoopPigExecuteOperator:"可执行Pig脚本",
        HadoopDecisionTreeOperator:"决策树",
        RandomForestOperator:"随机森林",
        RandomForestPredictOperator:  "随机森林预测",
        HadoopPivotOperator:"透视分析",
        HadoopColumnFilterOperator:"列筛选器",
        HadoopDecisionTreePredictOperator:"树预测",
        HadoopNaiveBayesOperator:"朴素贝叶斯",
        HadoopNaiveBayesPredictOperator: "朴素贝叶斯预测",
        HadoopConfusionOperator:"Confusion Matrix"



    })
//end v1.x content
);
