define({ root:
//begin v1.x content
        ({
        	
    DbTableOperator:"Dataset",
    BarChartAnalysisOperator:"Bar Chart",
    CorrelationAnalysisOperator:"Correlation",
    FrequencyAnalysisOperator:"Frequency",
    HistogramOperator:"Histogram",
    InformationValueAnalysisOperator:"Information Value",
    UnivariateOperator:"Univariate Operator",
    ValueAnalysisOperator:"Summary Statistics",
    AggregateOperator:"Aggregation",
    CustomizedOperator:"Custom Operator",
    NormalizationOperator:"Normalization",
    ReplaceNullOperator:"Null Value Replacement",
    IntegerToTextOperator:"Numeric to Text",
    PivotOperator:"Pivot",
    FilterOperator:"Row Filter",
    TableJoinOperator:"Join",
    VariableOperator:"Variable",
    RandomSamplingOperator:"Random Sampling",
    StratifiedSamplingOperator:"Stratified Sampling",
    SampleSelectorOperator:"Sample Selector",
    AssociationOperator:"Association Rules",
    CartOperator:"CART",
    DecisionTreeOperator:"Decision Tree",
    KMeansOperator:"K-Means",
    LinearRegressionOperator:"Linear Regression",
    LogisticRegressionOperator:"Logistic Regression",
    ModelOperator:"Model Save",
    NaiveBayesOperator:"Naive Bayes",
    NeuralNetworkOperator:"Neural Network",
    TimeSeriesOperator:"Time Series",
    LinearRegressionPredictOperator:"Linear Regression Predictor",
    LogisticRegressionPredictOperator:"Logistic Regression Predictor",
    NaiveBayesPredictOperator:"Naive Bayes Predictor",
    NeuralNetworkPredictOperator:"Neural Network Predictor",
    TimeSeriesPredictOperator:"Time Series Predictor",
    TreePredictOperator:"Tree Predictor",
    GoodnessOfFitOperator:"Goodness of Fit",
    LIFTOperator:"Lift",
    ROCOperator:"ROC",
    ProductRecommendationOperator:"Product Recommendation",
    ProductRecommendationEvaluationOperator:"Production Evaluation",
    SVMNoveltyDetectionOperator:"SVM Novelty Detection",
    SVMClassificationOperator:"SVM Classification",
    SVMRegressionOperator:"SVM Regression",
    SVMPredictOperator:"SVM Predictor",
    SVDOperator:"SVD",
    SVDLanczosOperator:"SVD",
    SVDCalculatorOperator:"SVD Calculator",
    SVDLanczosCalculatorOperator:"SVD Calculator",
    ColumnFilterOperator:"Column Filter",
    VariableSelectionAnalysisOperator:"Variable Selection",
    SQLExecuteOperator:"SQL Execute",
    AdaboostOperator:"Adaboost",
    AdaboostPredictOperator:"Adaboost Predictor",
    PCAOperator:"PCA",
    WOEOperator:"Weight of Evidence",
    WOETableGeneratorOperator:"WOE Table Generator",
    ScatterMatrixOperator:"Scatter Plot Matrix",
    TableSetOperator:"Set Operations",
    PLDATrainerOperator:"LDA",
    PLDAPredictOperator:"LDA Predictor",
    SubFlowOperator:"Sub-Flow",
    EMClusteringOperator:"EM Cluster",
    EMClusteringPredictOperator:"EM Cluster Predictor",
    ScatterPlotOperator:"Scatter Plot",
    UnivariateExplorerOperator:"Univariate",
    UnivariateOperator:"Univariate",
    BoxAndWhiskerOperator:"Box Plot",
    HadoopBoxAndWiskerOperator:"Box Plot",
    HadoopFileOperator:"Hadoop File",
    HadoopRowFilterOperator:"Row Filter",
    HadoopVariableOperator:"Variable",
    HadoopAggregateOperator:"Aggregation",
    HadoopFrequencyAnalysisOperator:"Frequency",
    HadoopValueAnalysisOperator:"Summary Statistics",
    HadoopHistogramOperator:"Histogram",
    HadoopUnionOperator:"Set Operations",
    HadoopJoinOperator:"Join",
    HadoopBarChartOperator:"Bar Chart",
    HadoopReplaceNullOperator:"Null Value Replacement",
    HadoopScatterPlotMatrixOperator:"Scatter Plot Matrix",
    HadoopNormalizationOperator:"Normalization",
    HadoopKmeansOperator:"K-Means",
    HadoopRandomSamplingOperator:"Random Sampling",
    HadoopSampleSelectorOperator:"Sample Selector",
    HadoopLinearRegressionOperator:"Linear Regression",
    HadoopLinearRegressionPredictOperator:"Linear Regression Predictor",
    HadoopLogisticRegressionOperator:"Logistic Regression",
    HadoopLogisticRegressionPredictOperator:"Logistic Regression Predictor",
    HadoopTimeSeriesOperator:"Time Series",
    HadoopTimeSeriesPredictOperator:"Time Series Predictor",
    HadoopVariableSelectionAnalysisOperator:"Variable Selection",
    CopyToDBOperator:"Copy to Database",
    CopytoHadoopOperator:"Copy to Hadoop",
    NoteOperator:"Note",
    HadoopROCOperator:"ROC",
    HadoopLiftOperator:"Lift",
    HadoopGoodnessOfFitOperator:"Goodness of Fit",
    HadoopPigExecuteOperator:"Pig Execute",
    HadoopDecisionTreeOperator :"Decision Tree",
    RandomForestOperator:  "Random Forest",
    RandomForestPredictOperator:  "Random Forest Predictor",
    HadoopPivotOperator:"Pivot",
    HadoopColumnFilterOperator:"Column Filter",
    HadoopDecisionTreePredictOperator:"Tree Predictor",
    HadoopNaiveBayesOperator:"Naive Bayes",
    HadoopNaiveBayesPredictOperator: "Naive Bayes Predictor",
    HadoopConfusionOperator:"Confusion Matrix"

        }),
    "zh": true,
    "ja": true
});